void main() {

try{
int number1 = 30;
int number2 = 0;
int result = number1 ~/number2;

print("Result of first number divided on second number is $result ");

}
catch(e){
  print("Exception occurs");
}
finally{
  print("finally block execute");
}

}
